### ISSUE TITLE
"Includes" and "excludes" like operators for string matching

### ISSUE THREAD

**Issue by wwqrd** [complexdatacollective/networkQuery#24]
Users would like non-exact matchers for strings.

Includes/excludes are already used for array comparisons, so we either:
- we need string specific terminology/precidate for strings
- we need to add type checking in the existing precidate

There is a possibility of adding more complex functionality such as regexp matching, since this could be made backwards compatible with string matchers.

**Comment by jthrilly** [comment]
Implemented in https://github.com/complexdatacollective/networkQuery/pull/44
